[build-system]
requires = ["setuptools>=61.0", "setuptools-scm[toml]>=8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ha-ocpp-relay"
dynamic = ["version"]
description = "OCPP relay with Home Assistant native integration."
authors = [{ name = "Michael Adler" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pyyaml>=6.0",
  "websockets>=15.0.1"
]

[project.scripts]
ocpp-relay-server = "relay_server.ocpp_relay_server:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["relay_server", "relay_server.*"]

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
local_scheme = "no-local-version"
